# Generated by Django 5.1 on 2024-08-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('callsign', models.CharField(max_length=50)),
                ('founded_year', models.IntegerField()),
                ('base_airport', models.CharField(max_length=50)),
            ],
        ),
    ]
