# Generated by Django 5.1 on 2024-08-20 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_serial_number', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('number_of_engines', models.IntegerField()),
                ('operator_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='airline.airline')),
            ],
        ),
    ]
